"use client"
import './globals.css'
import { Inter } from 'next/font/google'

import { Footer } from '../../components/footer/footer'
import { Header } from '../../components/header/header'
import { StoreProvider } from '../../redux/StoreProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="test">
      <link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@0,600;1,400&family=Roboto:wght@400;700&display=swap" rel="stylesheet"/>
      <div className="cont">
        <StoreProvider>
      <Header />
      <div id='root'></div>
      {children}
        </StoreProvider>
        <Footer />
        </div>
      </body>
    </html>
  )
}
